In [2]:
import numpy as np
import pandas as pd
heroes = pd.read_csv("heroes_information.csv")

In [3]:
###instalar desde anaconda navigator######
from pandasql import *

In [7]:
pysqldf = lambda q: sqldf(q,globals())

In [10]:
query2 = " SELECT * FROM heroes limit 10"

In [11]:
pysqldf(query2)

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,None,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,None,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,None,bad,-99.0
5,5,Absorbing Man,Male,blue,Human,No Hair,193.0,Marvel Comics,None,bad,122.0
6,6,Adam Monroe,Male,blue,None,Blond,-99.0,NBC - Heroes,None,good,-99.0
7,7,Adam Strange,Male,blue,Human,Blond,185.0,DC Comics,None,good,88.0
8,8,Agent 13,Female,blue,None,Blond,173.0,Marvel Comics,None,good,61.0
9,9,Agent Bob,Male,brown,Human,Brown,178.0,Marvel Comics,None,good,81.0

In [12]:
query1 = " SELECT name, Gender  FROM heroes limit 2"

In [13]:
pysqldf(query1)

         name Gender
0      A-Bomb   Male
1  Abe Sapien   Male

In [14]:
query3 = " SELECT name from heroes"

In [15]:
pysqldf(query3)

                name
0             A-Bomb
1         Abe Sapien
2           Abin Sur
3        Abomination
4            Abraxas
..               ...
729  Yellowjacket II
730             Ymir
731             Yoda
732          Zatanna
733             Zoom

[734 rows x 1 columns]

In [16]:
query4 = " SELECT distinct publisher FROM heroes"

In [17]:
pysqldf(query4)

            Publisher
0       Marvel Comics
1   Dark Horse Comics
2           DC Comics
3        NBC - Heroes
4           Wildstorm
5        Image Comics
6                None
7         Icon Comics
8                SyFy
9       Hanna-Barbera
10       George Lucas
11       Team Epic TV
12         South Park
13      HarperCollins
14        ABC Studios
15  Universal Studios
16          Star Trek
17     IDW Publishing
18           Shueisha
19      Sony Pictures
20      J. K. Rowling
21        Titan Books
22          Rebellion
23          Microsoft
24   J. R. R. Tolkien

In [52]:
query5 = " SELECT * FROM heroes where height>200"

In [53]:
pysqldf(query5)

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,None,good,441.0
1,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,None,bad,441.0
2,17,Alien,Male,None,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0
3,19,Amazo,Male,red,Android,None,257.0,DC Comics,None,bad,173.0
4,29,Ant-Man,Male,blue,Human,Blond,211.0,Marvel Comics,None,good,122.0
5,33,Anti-Venom,Male,blue,Symbiote,Blond,229.0,Marvel Comics,None,None,358.0
6,34,Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0
7,59,Bane,Male,None,Human,None,203.0,DC Comics,None,bad,180.0
8,78,Beta Ray Bill,Male,None,None,No Hair,201.0,Marvel Comics,None,good,216.0
9,119,Bloodaxe,Female,blue,Human,Brown,218.0,Marvel Comics,None,bad,495.0
10,144,Cable,Male,blue,Mutant,White,203.0,Marvel Comics,None,good,158.0
11,166,Century,Male,white,Alien,White,201.0,Marvel Comics,grey,good,97.0
12,179,Cloak,Male,brown,None,black,226.0,Marvel Comics,None,good,70.0
13,184,Colossus,Male,silver,Mutant,Black,226.0,Marvel Comics,None,good,225.0
14,203,Darkseid,Male,red,New God,No Hair,267.0,DC Comics,grey,bad,817.0
15,221,Doctor Doom,Male,brown,Human,Brown,201.0,Marvel Comics,None,bad,187.0
16,222,Doctor Doom II,Male,brown,None,Brown,201.0,Marvel Comics,None,bad,132.0
17,229,Doomsday,Male,red,Alien,White,244.0,DC Comics,None,bad,412.0
18,255,Fin Fang Foom,Male,red,Kakarantharaian,No Hair,975.0,Marvel Comics,green,good,18.0
19,270,Frenzy,Female,brown,None,Black,211.0,Marvel Comics,None,bad,104.0
20,272,Galactus,Male,black,Cosmic Entity,Black,876.0,Marvel Comics,None,neutral,16.0
21,302,Groot,Male,yellow,Flora Colossus,None,701.0,Marvel Comics,None,good,4.0
22,320,Hela,Female,green,Asgardian,Black,213.0,Marvel Comics,None,bad,225.0
23,321,Hellboy,Male,gold,Demon,Black,259.0,Dark Horse Comics,None,good,158.0
24,331,Hulk,Male,green,Human / Radiation,Green,244.0,Marvel Comics,green,good,630.0
25,373,Juggernaut,Male,blue,Human,Red,287.0,Marvel Comics,None,neutral,855.0
26,377,K-2SO,Male,white,Android,No Hair,213.0,George Lucas,gray,good,-99.0
27,386,Killer Croc,Male,red,Metahuman,No Hair,244.0,DC Comics,green,bad,356.0
28,388,Kilowog,Male,red,Bolovaxian,No Hair,234.0,DC Comics,pink,good,324.0
29,391,Kingpin,Male,blue,Human,No Hair,201.0,Marvel Comics,None,bad,203.0
30,412,Lizard,Male,red,Human,No Hair,203.0,Marvel Comics,None,bad,230.0
31,413,Lobo,Male,red,Czarnian,Black,229.0,DC Comics,blue-white,neutral,288.0
32,428,Man-Thing,Male,red,None,No Hair,213.0,Marvel Comics,green,good,225.0
33,432,Martian Manhunter,Male,red,Martian,No Hair,201.0,DC Comics,green,good,135.0
34,435,Master Chief,Male,brown,Human / Altered,Brown,213.0,Microsoft,None,good,-99.0
35,463,MODOK,Male,white,Cyborg,Brownn,366.0,Marvel Comics,None,bad,338.0
36,476,Mr Incredible,Male,blue,Human,Blond,201.0,Dark Horse Comics,None,good,158.0
37,498,Odin,Male,blue,God / Eternal,White,206.0,Marvel Comics,None,good,293.0
38,500,Omega Red,Male,red,None,Blond,211.0,Marvel Comics,None,bad,191.0
39,504,Onslaught,Male,red,Mutant,No Hair,305.0,Marvel Comics,None,bad,405.0
40,527,Predator,Male,None,Yautja,None,213.0,Dark Horse Comics,None,bad,234.0
41,549,Red Hulk,Male,yellow,Human / Radiation,Black,213.0,Marvel Comics,red,neutral,630.0
42,557,Rey,Female,hazel,Human,Brown,297.0,George Lucas,None,good,-99.0
43,575,Sasquatch,Male,red,None,Orange,305.0,Marvel Comics,None,good,900.0
44,576,Sauron,Male,None,Maiar,None,279.0,J. R. R. Tolkien,None,bad,-99.0
45,583,Scorpion,Male,brown,Human,Brown,211.0,Marvel Comics,None,bad,310.0
46,591,She-Hulk,Female,green,Human,Green,201.0,Marvel Comics,None,good,315.0
47,603,Sinestro,Male,black,Korugaran,Black,201.0,DC Comics,red,neutral,92.0
48,611,Solomon Grundy,Male,black,Zombie,White,279.0,DC Comics,None,bad,437.0
49,614,Spawn,Male,brown,Demon,Black,211.0,Image Comics,None,good,405.0
50,637,Steel,Male,brown,None,No Hair,201.0,DC Comics,None,good,131.0
51,657,Thanos,Male,red,Eternal,No Hair,201.0,Marvel Comics,purple,bad,443.0
52,667,Thundra,Female,green,None,Red,218.0,Marvel Comics,None,good,158.0
53,682,Ultron,Male,red,Android,None,206.0,Marvel Comics,silver,bad,331.0
54,691,Venom III,Male,brown,Symbiote,Brown,229.0,Marvel Comics,None,bad,334.0
55,692,Venompool,Male,None,Symbiote,None,226.0,Marvel Comics,None,None,-99.0
56,709,Warpath,Male,brown,Mutant,Black,218.0,Marvel Comics,None,good,158.0
57,718,Wolfsbane,Female,green,None,Auburn,366.0,Marvel Comics,None,good,473.0
58,730,Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0

In [50]:
query6 = " SELECT * FROM heroes where Race='Human' and Height>200"

In [51]:
pysqldf(query6)

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,None,good,441.0
1,29,Ant-Man,Male,blue,Human,Blond,211.0,Marvel Comics,None,good,122.0
2,59,Bane,Male,None,Human,None,203.0,DC Comics,None,bad,180.0
3,119,Bloodaxe,Female,blue,Human,Brown,218.0,Marvel Comics,None,bad,495.0
4,221,Doctor Doom,Male,brown,Human,Brown,201.0,Marvel Comics,None,bad,187.0
5,373,Juggernaut,Male,blue,Human,Red,287.0,Marvel Comics,None,neutral,855.0
6,391,Kingpin,Male,blue,Human,No Hair,201.0,Marvel Comics,None,bad,203.0
7,412,Lizard,Male,red,Human,No Hair,203.0,Marvel Comics,None,bad,230.0
8,476,Mr Incredible,Male,blue,Human,Blond,201.0,Dark Horse Comics,None,good,158.0
9,557,Rey,Female,hazel,Human,Brown,297.0,George Lucas,None,good,-99.0
10,583,Scorpion,Male,brown,Human,Brown,211.0,Marvel Comics,None,bad,310.0
11,591,She-Hulk,Female,green,Human,Green,201.0,Marvel Comics,None,good,315.0

In [42]:
query7 = " SELECT * FROM heroes where weight between 100 and 200 "

In [43]:
pysqldf(query7)

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,5,Absorbing Man,Male,blue,Human,No Hair,193.0,Marvel Comics,None,bad,122.0
1,10,Agent Zero,Male,None,None,None,191.0,Marvel Comics,None,good,104.0
2,11,Air-Walker,Male,blue,None,White,188.0,Marvel Comics,None,bad,108.0
3,17,Alien,Male,None,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0
4,19,Amazo,Male,red,Android,None,257.0,DC Comics,None,bad,173.0
...,...,...,...,...,...,...,...,...,...,...,...
93,709,Warpath,Male,brown,Mutant,Black,218.0,Marvel Comics,None,good,158.0
94,716,Winter Soldier,Male,brown,Human,Brown,175.0,Marvel Comics,None,good,117.0
95,719,Wolverine,Male,blue,Mutant,Black,160.0,Marvel Comics,None,good,135.0
96,721,Wonder Man,Male,red,None,Black,188.0,Marvel Comics,None,good,171.0
97,724,Wyatt Wingfoot,Male,brown,None,Black,196.0,Marvel Comics,None,good,117.0

In [91]:
query8 = " SELECT * FROM heroes where [Eye color]= 'red' or [Eye color]= 'blue'"

In [92]:
pysqldf(query8)

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
1,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
2,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,None,bad,-99.0
3,5,Absorbing Man,Male,blue,Human,No Hair,193.0,Marvel Comics,None,bad,122.0
4,6,Adam Monroe,Male,blue,None,Blond,-99.0,NBC - Heroes,None,good,-99.0
...,...,...,...,...,...,...,...,...,...,...,...
266,727,Yellow Claw,Male,blue,None,No Hair,188.0,Marvel Comics,None,bad,95.0
267,728,Yellowjacket,Male,blue,Human,Blond,183.0,Marvel Comics,None,good,83.0
268,729,Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,None,good,52.0
269,732,Zatanna,Female,blue,Human,Black,170.0,DC Comics,None,good,57.0
270,733,Zoom,Male,red,None,Brown,185.0,DC Comics,None,bad,81.0

In [80]:
query9 = " SELECT * FROM heroes where 'Eye color'= 'red' or 'Eye color'= 'blue'"

In [81]:
pysqldf(query9)

Empty DataFrame
Columns: [id, name, Gender, Eye color, Race, Hair color, Height, Publisher, Skin color, Alignment, Weight]
Index: []

In [64]:
query10 = " SELECT * FROM heroes order by Race desc   "

In [65]:
pysqldf(query10)

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,611,Solomon Grundy,Male,black,Zombie,White,279.0,DC Comics,None,bad,437.0
1,274,Gamora,Female,yellow,Zen-Whoberian,Black,183.0,Marvel Comics,green,good,77.0
2,731,Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0
3,527,Predator,Male,None,Yautja,None,213.0,Dark Horse Comics,None,bad,234.0
4,17,Alien,Male,None,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0
...,...,...,...,...,...,...,...,...,...,...,...
729,723,Wondra,Female,None,None,None,-99.0,Marvel Comics,None,good,-99.0
730,724,Wyatt Wingfoot,Male,brown,None,Black,196.0,Marvel Comics,None,good,117.0
731,726,X-Man,Male,blue,None,Brown,175.0,Marvel Comics,None,good,61.0
732,727,Yellow Claw,Male,blue,None,No Hair,188.0,Marvel Comics,None,bad,95.0
733,733,Zoom,Male,red,None,Brown,185.0,DC Comics,None,bad,81.0

In [68]:
query11 = " SELECT count(Gender) FROM heroes group by Gender  "

In [69]:
pysqldf(query11)

   count(Gender)
0              0
1            200
2            505

In [72]:
query12 = " SELECT count(*) FROM heroes group by Publisher having count()>15 "

In [73]:
pysqldf(query12)

   count(*)
0       215
1        18
2       388
3        19